# Port which adds VLAN
port: '0/5'

# IP address and netmask for host y.y.y.y
ipaddr: '20.0.0.2'
netmask: '255.255.255.0'

aclname: 'FILTER-ICMP'

aclentry:
  - 1000 deny icmp any any
  - 2000 permit ip any any
