- name: check if specified vlan had configured correctly
  hosts: all
  gather_facts: no
  connection: local
  
  vars:
    textfsm_template: 'textfsm_template/alaxala_handson_show_vlan.template'

  tasks:
    - name: show vlan detail
      ax_command:
        commands:
          - show vlan detail
        provider: "{{ cli }}"
      register: result

    - name: print show vlan detail information
      debug:
        var: result.stdout_lines

    - name: parse show vlan detail
      set_fact:
        vlan_parsed: '{{ result.stdout[0] | parse_cli_textfsm( textfsm_template ) }}'

    - name: print parsed show vlan detail information
      debug:
        var: vlan_parsed

    - name: check if vlan <vid> had configured on target hosts
      assert:
        that:
          - "'{{ vid }}' in (vlan_parsed | map(attribute='VLANID') | list)"
