- name: remove vlan
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: remove vlan configuration from port
      ax_config:
        lines:
          - switchport trunk allowed vlan remove {{ vid }}
          - no switchport mode trunk
        parents: "interface gigabitethernet {{ port }}"
        provider: "{{ cli }}"

    - name: remove "interface vlan <vid>"
      ax_config:
        lines:
          - no interface vlan {{ vid }}
        provider: "{{ cli }}"
        save_when: modified
