- name: remove configured ACL
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: remove from vlan interface
      ax_config:
        lines:
          - no ip access-group {{ aclname }} in
        parents: "interface vlan {{ vid }}"
        provider: "{{ cli }}"

    - name: remove "ip access-list extended <aclname>"
      ax_config:
        lines:
          - no ip access-list extended {{ aclname }}
        provider: "{{ cli }}"
        save_when: modified
