- name: configure "vlan <vid>"
  ax_config:
    lines:
      - vlan {{ vid }}

- name: configure "interface vlan <vid>"
  ax_config:
    lines:
      - ip address {{ ipaddr }} {{ netmask }}
    parents: "interface vlan {{ vid }}"

- name: vlan configuration to port
  ax_config:
    lines:
      - switchport mode trunk
      - switchport trunk allowed vlan add {{ vid }} 
    parents: "interface gigabitethernet {{ port }}"
    save_when: modified
