- name: configure ACL to vlan interface
  hosts: L2
  gather_facts: no
  connection: network_cli

  tasks:
    - name: configure "ip access-list extended <acl name>"
      ax_config:
        lines: "{{ aclentry }}"
        parents: "ip access-list extended {{ aclname }}"

    - name: attach to interface vlan
      ax_config:
        lines:
          - ip access-group {{ aclname }} in
        parents: "interface vlan {{ vid }}"
        save_when: modified
