- name: remove configured ACL
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: remove from vlan interface
      ax_config:
        lines:
          - no ip access-group {{ aclname }} in
        parents: "interface vlan {{ vid }}"

    - name: remove "ip access-list extended <aclname>"
      ax_config:
        lines:
          - no ip access-list extended {{ aclname }}
        save_when: modified
