- name: remove vlan
  hosts: L2
  gather_facts: no
  connection: network_cli

  tasks:

    - name: remove vlan configuration from port
      ax_config:
        lines:
          - switchport trunk allowed vlan remove {{ vid }}
          - no switchport mode trunk
        parents: "interface gigabitethernet {{ port }}"

    - name: remove "interface vlan <vid>"
      ax_config:
        lines:
          - no interface vlan {{ vid }}
        save_when: modified
